const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('ck', {
    http: (opts) => ipcRenderer.invoke('http', opts),
    service: () => ipcRenderer.invoke('service'),
    version: () => ipcRenderer.invoke('version'),
    platform: process.platform,
    openExternal: (url) => ipcRenderer.invoke('openExternal', url),
    play: (opts) => ipcRenderer.invoke('play', opts),
    stopPlay: () => ipcRenderer.invoke('stopPlay'),
    onMpvExit: (cb) => ipcRenderer.on('mpv-exit', (_e, d) => cb(d)),
    onMpvDead: (cb) => ipcRenderer.on('mpv-dead-instant', (_e, d) => cb(d)),
    openTrailer: (id) => ipcRenderer.invoke('open-trailer', id),
    onUpdReady: (cb) => ipcRenderer.on('upd-ready', (_e, d) => cb(d)),
    applyUpdate: () => ipcRenderer.invoke('apply-update'),
    onMpvPos: (cb) => ipcRenderer.on('mpv-pos', (_e, d) => cb(d)),
    dlStart: (opts) => ipcRenderer.invoke('dl-start', opts),
    dlSize: (url) => ipcRenderer.invoke('dl-size', { url }),
    dlList: () => ipcRenderer.invoke('dl-list'),
    dlDelete: (key) => ipcRenderer.invoke('dl-delete', { key }),
    onDlProg: (cb) => ipcRenderer.on('dl-prog', (_e, d) => cb(d)),
    onDlDone: (cb) => ipcRenderer.on('dl-done', (_e, d) => cb(d)),
    onDlErr: (cb) => ipcRenderer.on('dl-err', (_e, d) => cb(d)),
});
